namespace UnifiedDirectoryManager.Models;

/// <summary>
/// The kind of cloud group to create. This also decides the backend, and that routing is mandatory rather than
/// an optimisation: Microsoft Graph returns 400 ("Cannot Create a mail-enabled security groups and or
/// distribution list") for the two mail-enabled kinds, which are managed only through Exchange Online.
/// </summary>
public enum CloudGroupType
{
    /// <summary>Cloud-only security group. Graph: mailEnabled false, securityEnabled true, groupTypes [].</summary>
    Security,

    /// <summary>Microsoft 365 (unified) group. Graph: groupTypes ["Unified"], mailEnabled true.</summary>
    Microsoft365,

    /// <summary>Distribution list. Exchange: <c>New-DistributionGroup -Type Distribution</c>.</summary>
    Distribution,

    /// <summary>Mail-enabled security group. Exchange: <c>New-DistributionGroup -Type Security</c>.</summary>
    MailEnabledSecurity,
}

/// <summary>
/// One member or owner chosen for a new cloud group, carrying both identifiers because the two backends address
/// objects differently: Graph binds by directory object id, Exchange resolves by SMTP address.
/// </summary>
/// <param name="Id">Entra object id (the Graph path).</param>
/// <param name="Address">Primary SMTP or UPN (the Exchange path); empty when the object has no mail identity.</param>
public sealed record CloudGroupPrincipal(string Id, string DisplayName, string Address);

/// <summary>Everything the New Cloud Group dialog collects, in a shape both backends can consume.</summary>
public sealed record CloudGroupCreateRequest
{
    public required CloudGroupType Type { get; init; }
    public required string DisplayName { get; init; }

    /// <summary>Graph <c>mailNickname</c> / Exchange <c>Alias</c>. Required by Graph even for a mail-disabled
    /// security group; generated by Exchange from the name if omitted, which is why the dialog derives it.</summary>
    public required string MailNickname { get; init; }

    public string? Description { get; init; }

    /// <summary>Owners. An admin creating a security group with no owner gets an OWNERLESS group — Graph
    /// auto-assigns the caller only for Microsoft 365 groups, or when the caller isn't an admin.</summary>
    public IReadOnlyList<CloudGroupPrincipal> Owners { get; init; } = Array.Empty<CloudGroupPrincipal>();

    public IReadOnlyList<CloudGroupPrincipal> Members { get; init; } = Array.Empty<CloudGroupPrincipal>();

    /// <summary>Microsoft 365 only: "Public" or "Private". Ignored for the other kinds.</summary>
    public string Visibility { get; init; } = "Private";

    /// <summary>
    /// Hide the membership list. <b>Irreversible on both backends</b>, but not identically: Graph's
    /// <c>visibility: "HiddenMembership"</c> can only be set at creation, while Exchange's
    /// <c>-HiddenGroupMembershipEnabled</c> can be turned on later and then never off — Microsoft's wording is
    /// "you can't edit the group later to reveal the membership". Either way there is no way back.
    /// </summary>
    public bool HiddenMembership { get; init; }

    /// <summary>
    /// Exchange kinds only. Exchange's own flag is <c>RequireSenderAuthenticationEnabled</c>, which defaults to
    /// <c>$true</c> — meaning a new list silently rejects all external mail. This is stated the way an operator
    /// thinks about it, and the service call inverts it.
    /// </summary>
    public bool AllowExternalSenders { get; init; }

    /// <summary>
    /// Microsoft 365 only. A new Microsoft 365 group emails every initial member a welcome notification unless
    /// the create body's <c>resourceBehaviorOptions</c> carries <c>WelcomeEmailDisabled</c>. That collection is
    /// POST-only, so this is unfixable afterwards — and the mail has already gone to real people.
    /// <b>Default off</b>: an admin building a group from a directory tool is not announcing it.
    /// </summary>
    public bool SendWelcomeEmail { get; init; }

    /// <summary>
    /// Microsoft 365 only, and POST-only for the same reason as <see cref="SendWelcomeEmail"/>
    /// (<c>resourceBehaviorOptions: HideGroupInOutlook</c>). Not to be confused with Graph's similarly-named
    /// <c>hideFromOutlookClients</c>, which is stored outside the main directory and is documented as
    /// unsettable in a create body at all.
    /// </summary>
    public bool HideInOutlook { get; init; }
}

/// <summary>
/// Outcome of creating a cloud group. The group EXISTS whenever this is returned — the optional error strings
/// are non-fatal failures of the separate follow-up writes (owners and members are their own requests and can
/// fail on their own, e.g. against tenant policy or the directory replication window), so callers must report
/// the group as created and surface these as warnings rather than as a failed create.
/// </summary>
public sealed record CloudGroupCreateResult(
    string Id,
    string DisplayName,
    string? OwnersError = null,
    string? MembersError = null)
{
    /// <summary>The follow-up steps that didn't complete, phrased for the operator; empty when all succeeded.</summary>
    public IReadOnlyList<string> Warnings
    {
        get
        {
            var list = new List<string>();
            if (OwnersError is not null) list.Add("These owners were not set: " + OwnersError);
            if (MembersError is not null) list.Add("These members were not added: " + MembersError);
            return list;
        }
    }
}
